default_language_version:
  # Keep in sync with test.yml/PYTHON_LATEST
  python: python3.13

ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # keep in sync with .github/workflows/ruff.yml
    rev: 'v0.12.11'
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
